---
- name: Pull Gitea Docker Image
  docker_image: 
    name: gitea/gitea:latest
    state: present

- name: Build and Run Gitea Container
  docker_container:
    name: gitea
    image: gitea/gitea:latest
    purge_networks: yes
    keep_volumes: true
    networks:
      - name: "{{ PROXY_NETWORK }}"
    pull: no
    restart_policy: unless-stopped
    env:
      USER_UID: "{{ USER_UID }}"
      USER_GID: "{{ USER_GID }}"
      GITEA__database__DB_TYPE: "{{ DB_TYPE }}"
      GITEA__database__HOST: "{{ DB_HOST }}"
      GITEA__database__NAME: "{{ DB_NAME }}"
      GITEA__database__USER: "{{ DB_USER }}"
      GITEA__database__PASSWD: "{{ DB_PASS }}"
    volumes:
    - "{{ GITEA_PATH }}:/data"
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
      "{{ GITEA_PORTS }}"