---
- name: Build All Docker Containers
  hosts: pfnass
  roles:
    - pfnass-docker-networks
    - pfnass-traefik-tailscale-proxy
    - pfnass-docker-db
    - pfnass-plex-server
    - pfnass-vscode
    - pfnass-vaultwarden
    - pfnass-jellyfin
    - pfnass-mealie
  become: true

# - name: Define Docker Networks and Tailscale + Proxy
#   hosts: pfnass
#   # tags: [networks]
#   roles:
#     - pfnass-docker-networks
#     - pfnass-traefik-tailscale-proxy
#   become: true
