---
- name: Pull VaultWarden Docker Image
  community.docker.docker_image:
    name: vaultwarden/server:latest
    state: present
    source: pull
  tags:
    - docker
    - image
    - vault

- name: Start VaultWarden Container
  community.docker.docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    keep_volumes: true
    networks:
      - name: "{{ proxy_network }}"
    pull: false
    restart_policy: unless-stopped
    env:
      # ADMIN_TOKEN: "{{ ADMIN_TOKEN }}"
      # WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      DOMAIN: "{{ domain }}"
    volumes:
      - "{{ vw_path }}:/data:rw"
    ports:
      "{{ vw_port }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.warden.rule: Host(`warden.pfnass.online`)
      traefik.http.routers.warden.entrypoints: websecure
      traefik.http.routers.warden.tls.certresolver: myresolver
  tags:
    - docker
    - container
    - vault
