---
# - name: Pull MySQL Database Image
#   docker_image:
#     name: gitea/gitea:latest
#     state: present

# - name: Build and Run MySQL Database Container
#   docker_container:
#     name: mysql
#     purge_networks: yes
#     keep_volumes: true
#     image: mysql:8
#     hostname: mysql
#     networks:
#     - name: "{{ PROXY_NETWORK }}"
#     pull: no
#     restart_policy: unless-stopped
#     env:
#       MYSQL_ROOT_PASSWORD: "{{ DB_ROOT_PASS }}"
#       MYSQL_USER: "{{ DB_USER }}"
#       MYSQL_PASSWORD: "{{ DB_PASS }}"
#       MYSQL_DATABASE: "{{ DB_NAME }}"
#     volumes:
#     - "{{ MYSQL_PATH }}:/var/lib/mysql"
#     ports:
#       "{{ MYSQL_PORTS }}"

- name: Pull Postgres Database Image
  community.docker.docker_image:
    name: postgres:15
    source: pull
    pull:
      platform: arm64
  tags:
    - docker
    - image
    - postgres

- name: Run Postgres Database Container
  community.docker.docker_container:
    name: postgres
    image: postgres:latest
    networks:
      - name: "{{ proxy_network }}"
    restart_policy: unless-stopped
    ports:
      - "{{ postgres_ports }}"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
    volumes:
      - "{{ postgres_volume_path }}/data:/var/lib/postgresql/data"
      - "{{ postgres_volume_path }}/init_multi_db.sh:/docker-entrypoint-initdb.d/init_multi_db.sh"
  tags:
    - docker
    - container
    - postgres
