---
- name: Pull Mealie Docker Image
  docker_image: 
    name: ghcr.io/mealie-recipes/mealie:latest
    state: present
    source: pull

- name: Run Mealie Container
  docker_container:
    name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    purge_networks: yes
    keep_volumes: true
    networks:
      - name: "{{ MEALIE_NETWORK }}"
    pull: no
    restart_policy: unless-stopped
    env:
      USER_UID: "{{ USER_UID }}"
      USER_GID: "{{ USER_GID }}"
      ALLOW_SIGNUP: "false"
      TZ: America/Chicago
      BASE_URL: http://192.168.1.189:9925
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: mealie
    volumes:
    - "{{ MEALIE_VOLUME_PATH }}:/app/data/"
    ports:
      "{{ MEALIE_PORTS }}"