---
- name: Pull Mealie Docker Image
  community.docker.docker_image:
    name: ghcr.io/mealie-recipes/mealie:latest
    state: present
    source: pull
  tags:
    - docker
    - image
    - mealie

- name: Run Mealie Container
  community.docker.docker_container:
    name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    keep_volumes: true
    networks:
      - name: "{{ proxy_network }}"
    pull: false
    restart_policy: unless-stopped
    env:
      USER_UID: "{{ user_uid }}"
      USER_GID: "{{ user_gid }}"
      ALLOW_SIGNUP: "false"
      TZ: America/Chicago
      BASE_URL: "{{ base_url }}"
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: pfnass
      POSTGRES_PASSWORD: "{{ db_pass }}"
      POSTGRES_SERVER: "192.168.1.189"
      POSTGRES_PORT: "5433"
      POSTGRES_DB: mealie
    volumes:
      - "{{ mealie_volume_path }}/data:/app/data/"
    ports:
      - "{{ mealie_ports }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.mealie.rule: Host(`mealie.pfnass.online`)
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.routers.mealie.tls.certresolver: myresolver
  tags:
    - docker
    - container
    - mealie
