---
- name: Pull Jellyfin Docker Image
  community.docker.docker_image:
    name: jellyfin/jellyfin
    state: present
    source: pull
  tags:
    - docker
    - image
    - jellyfin

- name: Start Jellyfin Container
  community.docker.docker_container:
    name: jellyfin
    image: jellyfin/jellyfin
    purge_networks: true
    keep_volumes: true
    networks:
      - name: "{{ proxy_network }}"
    pull: false
    restart_policy: unless-stopped
    env:
      TZ: America/Chicago
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
    volumes:
      - "{{ jellyfin_path }}/config:/config"
      - "{{ jellyfin_path }}/cache:/cache"
      - "{{ jellyfin_media }}:/Media"
    ports:
      "{{ jellyfin_port }}"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.pfnass.online`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls.certresolver: myresolver
  tags:
    - docker
    - container
    - jellyfin
