---
- name: Pull Jellyfin Docker Image
  docker_image: 
    name: jellyfin/jellyfin
    state: present

- name: Start Jellyfin Container
  docker_container:
    name: jellyfin
    image: jellyfin/jellyfin
    purge_networks: yes
    keep_volumes: true
    networks:
      - name: "{{ PROXY_NETWORK }}"
    pull: no
    restart_policy: unless-stopped
    env:
      TZ: America/Chicago
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    volumes:
      - "{{ JELLYFIN_PATH }}/config:/config"
      - "{{ JELLYFIN_PATH }}/cache:/cache"
      - "{{ JELLYFIN_MEDIA }}:/Media"
    ports:
      "{{ JELLYFIN_PORT }}"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0