---
- name: Pull Tailscale Docker Image
  docker_image: 
    name: tailscale/tailscale:latest
    state: present

- name: Build and Run Tailscale Container
  docker_container:
    name: tailscaled
    image: tailscale/tailscale
    purge_networks: yes
    keep_volumes: true
    networks:
      - name: "{{ PROXY_NETWORK }}"
    pull: no
    restart_policy: unless-stopped
    capabilities:
      - NET_ADMIN
      - NET_RAW
    env:
        TS_STATE_DIR: "{{ TS_STATE_DIR }}"
        TS_AUTH_KEY: "{{ TS_AUTH_KEY }}"
        TS_EXTRA_ARGS: "{{ TS_EXTRA_ARGS }}"
        TS_SOCKET: "{{ TS_SOCKET }}"
    volumes:
      - /dev/net/tun:/dev/net/tun
      - "{{ TAILSCALE_PATH }}/varlib:/var/lib"
      - "{{ TAILSCALE_PATH }}/tmp:/tmp"

- name: Build Caddy Proxy Image
  docker_image:
    build:
      path: "{{ CADDY_PATH }}"
    name: caddy-local
    state: present

- name: Run Caddy Proxy Container
  docker_container:
    name: caddy
    image: caddy-local
    keep_volumes: true
    purge_networks: yes
    networks:
      - name: "{{ PROXY_NETWORK }}"
    pull: no
    restart_policy: unless-stopped
    env:
        MY_DOMAIN: "{{ MY_DOMAIN }}"
        MY_HOST_IP: "{{ MY_HOST_IP }}"
        VW_HOST_IP: "{{ VW_HOST_IP}}"
        WIKI_HOST_IP: "{{ WIKI_HOST_IP }}"
        CLOUDFLARE_API_TOKEN: "{{ CLOUDFLARE_API_TOKEN }}"
    volumes:
      - "{{ CADDY_PATH }}/Caddyfile:/etc/caddy/Caddyfile"
      - "{{ CADDY_PATH }}/data:/data"
      - "{{ CADDY_PATH }}/config:/config"
        # tailscale creates its socket on /tmp, so we'll kidnap from there to expose to caddy
      - "{{ TAILSCALE_PATH }}/tmp/tailscaled.sock:/var/run/tailscale/tailscaled.sock"