name: Run Ansible playbooks

on:
  workflow_dispatch:
    inputs:
      TAGS:
        description: 'Tags to run'
        type: string
        required: true

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run PFNASS Container Playbook
        env:
          ANSIBLE_USER: ${{ secrets.PFNASS_USER }}
          ANSIBLE_HOST_KEY_CHECKING: false
          ANSIBLE_PORT: ${{ secrets.PFNASS_PORT }}
          TAGS: ${{ inputs.TAGS }}
          PRIVATE_KEY: private_key.pem
        run: |
          ansible-playbook -i pfnass-ansible/inventory pfnass-ansible/playbooks/build_docker_containers_playbook.yml
