name: Run Ansible playbooks

on:
  workflow_dispatch:
    inputs:
      PLAYBOOK:
        description: 'Playbook to run'
        type: string
        required: true
      TAGS:
        description: 'Tags to run'
        type: string
        required: true

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Create Ansible Vault Password File
        run: |
          echo ${{ secrets.VAULT_PASSWORD }} >> .vault_pass

      - name: Run PFNASS Container Playbook
        env:
          ANSIBLE_USER: ${{ secrets.PFNASS_USER }}
          ANSIBLE_HOST_KEY_CHECKING: false
          ANSIBLE_PORT: ${{ secrets.PFNASS_PORT }}
          TAGS: ${{ inputs.TAGS }}
          PLAYBOOK: ${{ inputs.PLAYBOOK }}
          PRIVATE_KEY: private_key.pem
        run: |
          ansible-playbook \
          -i pfnass-ansible/inventory \
          pfnass-ansible/playbooks/build_docker_${{ inputs.PLAYBOOK }}_playbook.yml \
          -u ${{ secrets.ANSIBLE_USER }} \
          -e ANSIBLE_PORT=${{ secrets.PFNASS_PORT }} \
          --tags=${{ inputs.TAGS }} \
          --private-key ${{ env.PRIVATE_KEY }} \
          --vault-password-file=.vault_pass

      - name: Remove VAULT_PASSWORD
        if: always()
        run: |
          rm -f .vault_pass