name: Run Ansible playbooks

on:
  workflow_dispatch:
    inputs:
      USER:
        description: 'User to run in playbook'
        type: string
        required: true
      TAGS:
        description: 'Tags to run'
        type: string
        required: true

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ${{ inputs.USER }}
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i inventory/inventory playbooks/playbook.yml --private-key private_key.pem -u ${{ secrets.USER }} --tags="{{ inputs.TAGS }}"
